### ISSUE TITLE
align with ndarray

### ISSUE THREAD

**Issue by mattdesl** [shama/dtype#1]
would be cool to align with ndarray to avoid some subtle bugs that can crop up

e.g.
Uint8ClampedArray -> "uint8_clamped"
Buffer -> "buffer"

**Comment by mattdesl** [comment]
here is how zeros does it: https://github.com/mikolalysenko/zeros/blob/master/zeros.js#L5

**Comment by shama** [comment]
Thanks! Does a88241a look good? If so I'll publish a `1.0.0`

**Comment by mattdesl** [comment]
seems good to me! maybe @mikolalysenko would have more insight

**Comment by mattdesl** [comment]
@shama @mikolalysenko 
Maybe `"buffer"` should return Buffer?

**Comment by shama** [comment]
Sounds good or even `"buffer"` returns `Buffer` if globally available otherwise `ArrayBuffer` (for plain browser support)?

**Comment by shama** [comment]
btw @mattdesl added you as an owner

**Comment by mattdesl** [comment]
:+1: thanks !

**Comment by mattdesl** [comment]
Hmm one of the unfortunate side-effects is that it brings the bundle size up to 20kb :disappointed: Which affects modules like [array-pack-2d](https://www.npmjs.com/package/array-pack-2d) and [three-bmfont-text](https://github.com/Jam3/three-bmfont-text/blob/master/package.json) (was previously 8kb).

**Comment by shama** [comment]
Ah because of `Buffer` being detected by browserify I'm guessing? I wonder if there is a way I can make this lib not care about that but only include `Buffer` libs if the user is using it (as I would expect them to if they are trying to detect that type).

**Comment by mattdesl** [comment]
Hmm not sure really since it has to be statically analyzable for Browserify. 

I might end up just making another module called `array-dtype` or something that is specifically just arrays and typed arrays. Alternatively, we could revert the buffer stuff in `dtype` and make another module called `ndarray-dtype` which tries to align with ndarray modules (which already have Buffer in them anyways).

**Comment by shama** [comment]
That works too. Feel free to make whatever changes you need here, if needed.

**Comment by mattdesl** [comment]
k, I'll submit a PR in a bit
